# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
matrix:
  allow_failures:
    - julia: 0.7
notifications:
  email: true
# uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'ENV["PYTHON"]=""; Pkg.add("PyCall"); Pkg.build("PyCall")'
  - julia -e 'Pkg.add("Symata"); Pkg.checkout("Symata")'
  - julia -e 'Pkg.clone(pwd()); Pkg.build("NMfE"); Pkg.test("NMfE"; coverage=true)'
